// src/lib/themes.ts

export const themes = {
  blue: {
    name: "Professional Blue",
    primary: "from-blue-900 to-blue-700",
    accent: "bg-yellow-400",
    accentHover: "hover:bg-yellow-300",
    accentText: "text-yellow-400",
    textOnAccent: "text-blue-900",
    cardBg: "bg-blue-50",
    iconBg: "bg-blue-100",
    icon: "text-blue-600",
    border: "border-blue-200",
  },
  // orange: {
  //   name: "Industrial Orange",
  //   primary: "from-orange-700 to-orange-500",
  //   accent: "bg-gray-900",
  //   accentHover: "hover:bg-gray-800",
  //   accentText: "text-orange-400",
  //   textOnAccent: "text-white",
  //   cardBg: "bg-orange-50",
  //   iconBg: "bg-orange-100",
  //   icon: "text-orange-600",
  //   border: "border-orange-200",
  // },
  // dark: {
  //   name: "Modern Dark",
  //   primary: "from-gray-900 to-gray-800",
  //   accent: "bg-cyan-400",
  //   accentHover: "hover:bg-cyan-300",
  //   accentText: "text-cyan-400",
  //   textOnAccent: "text-gray-900",
  //   cardBg: "bg-gray-700",
  //   iconBg: "bg-cyan-900",
  //   icon: "text-cyan-400",
  //   border: "border-cyan-800",
  // },
  // green: {
  //   name: "Eco Tech",
  //   primary: "from-green-800 to-green-600",
  //   accent: "bg-lime-400",
  //   accentHover: "hover:bg-lime-300",
  //   accentText: "text-lime-400",
  //   textOnAccent: "text-green-900",
  //   cardBg: "bg-green-50",
  //   iconBg: "bg-green-100",
  //   icon: "text-green-600",
  //   border: "border-green-200",
  // },
  // red: {
  //   name: "Power Red",
  //   primary: "from-red-900 to-red-700",
  //   accent: "bg-amber-400",
  //   accentHover: "hover:bg-amber-300",
  //   accentText: "text-amber-400",
  //   textOnAccent: "text-red-900",
  //   cardBg: "bg-red-50",
  //   iconBg: "bg-red-100",
  //   icon: "text-red-600",
  //   border: "border-red-200",
  // },
} as const;

export type ThemeKey = keyof typeof themes;
